test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -384,21 +384,21 @@ jobs:
       - run: 
           name: run cleanup
           command: |
-            set +e
+            # set +e
             OldWorkflowID=1 #deleteme
-
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
-            then
+            try
               echo "I am here."
-              if aws s3 ls "s3://udapeople-${OldWorkflowID}" 2>/dev/null | grep 'NoSuchBucket' >/dev/null; then
-                echo "Bucket does not exist. Skipping deletion."  
-              else
-                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-              fi  
-            fi
-            set -e
+              aws s3 ls "s3://udapeople-${OldWorkflowID}"
+            catch 
+              echo "Cought error"
+
+            # if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+            # then
+            #     aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+            #     aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+            #     aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            # fi
+            # set -e
 workflows:
   default:
     jobs: 
